id: P000497
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-16 15:43:01.246267
source_metadata:
  id: bdr:W27888
  title: བསྐྱེད་རིམ་སྤྱིའི་རྣམ་བཞག
  author: ''
  volumes:
    d07de645c3d147ef81389ec91c4939af:
      image_group_id: I4682
      title: ''
      volume_number: 1
      total_pages: 194
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
